export enum DelegateKey {
  SOCIAL = 'social',
  WEBSITE = 'website',
  POSTS = 'posts',
  TOPIC = 'topic',
  MONITOR = 'monitor',
  SOCIAL_GROUP = 'socialGroup',
  SOCIAL_SOURCE = 'socialSource',
  SENTIMENT_KEYWORD = 'sentimentKeyword',
  SOCIAL_LOT = 'socialLot',
  SOCIAL_OBJ_MONITOR = 'socialObjMonitor',
  WEB_GROUP = 'webGroup',
  WEB_SOURCE = 'webSource',
  WEB_LOT = 'webLot',
  WEB_OBJ_MONITOR = 'webObjMonitor',
  SOCIAL_PRO_POST_MONITOR = 'socialProPostMonitor',
  SOCIAL_OBJ_POST_MONITOR = 'socialObjPostMonitor',
  WEB_PRO_POST_MONITOR = 'webProPostMonitor',
  WEB_OBJ_POST_MONITOR = 'webObjPostMonitor',
  MENTIONS = 'mentions',
  SENTIMENT = 'sentiment',
  RANKING = 'ranking',
  DEMOGRAPHIC = 'demographic',
  ACCOUNT = 'account',
  USER_GROUP = 'userGroup',
  USER = 'user',
  IMPORT_TEMPLATE = "importTemplate"
}

export enum RoleActionKey {
    VIEW = 'view',
    ADD = 'add',
    UPDATE = 'update',
    DELETE = 'delete',
    APPROVLE = 'approve',
    COPY = 'copy',
    EXPORT = 'export',
    ROLE = 'role',
    NOTE = 'note',
}