export const ERR_MESSAGE = {
  unauthorized: { value: 'UNAUTHORIZED', label: 'Không được phép truy cập' },
  forbidden: { value: 'FORBIDDEN', label: 'Không được phép truy cập' },
  user_invalid: { value: 'USER_INVALID', label: 'Tài khoản hoặc mật khẩu không đúng' },
  user_me_delete: { value: 'USER_ME_DELETE', label: 'Không thể xóa chính mình' },
  user_not_exist: { value: 'USER_NOT_EXIST', label: 'Tài khoản không tồn tại' },
  password_incorrect: { value: 'PASSWORD_INCORRECT', label: 'Mật khẩu cũ không đúng' },
  project_not_found: { value: 'PROJECT_NOT_FOUND', label: 'Không tìm thấy chuyên đề' },
  social_obj_not_found: { value: 'SOCIAL_OBJ_NOT_FOUND', label: 'Không tìm thấy đối tượng theo dõi mạng xã hội' },
  social_source_not_found: { value: 'SOCIAL_SOURCE_NOT_FOUND', label: 'Không tìm thấy nguồn thu thập mạng xã hội' },
  group_not_found: { value: 'GROUP_NOT_FOUND', label: 'Không tìm thấy nhóm' },
  post_not_found: { value: 'POST_NOT_FOUND', label: 'Không tìm thấy bài viết' },
  lot_not_found: { value: 'LOT_NOT_FOUND', label: 'Không tìm thấy lô' },
  website_obj_not_found: { value: 'WEBSITE_OBJ_NOT_FOUND', label: 'Không tìm thấy đối tượng theo dõi website' },
  website_source_not_found: { value: 'WEBSITE_SOURCE_NOT_FOUND', label: '"Không tìm thấy nguồn thu thập website"' },
  internal_server_error: { value: 'INTERNAL_SERVER_ERROR', label: 'Lỗi server vui lòng quay lại sau' },
  note_lock: { value: 'NOTE_LOCK', label: 'Đã khoá ghi chú' },
  lot_reference_exists: { value: 'LOT_REFERENCE_EXISTS', label: 'Không thể xóa lô nguồn thu thập do có dữ liệu tham chiếu' },
  group_reference_exists: { value: 'GROUP_REFERENCE_EXISTS', label: 'Không thể xóa nhóm thu thập do có dữ liệu tham chiếu' },
  notification_config_not_found: { value: 'NOTIFICATION_CONFIG_NOT_FOUND', label: 'Không tìm thấy cấu hình thông báo' },
  notification_config_reference_exists: { value: 'NOTIFICATION_CONFIG_REFERENCE_EXISTS', label: 'Không thể xoá do có dữ liệu tham chiếu đến cấu hình thông báo' },
  notification_not_found: { value: 'NOTIFICATION_NOT_FOUND', label: 'Không timg thấy thông báo' },
  times_type_incorrect: { value: 'TIMES_TYPE_INCORRECT', label: 'Loại thời gian thông báo không đúng' },
  send_time_incorrect: { value: 'SEND_TIME_INCORRECT', label: 'Thời gian thông báo không đúng' },
  send_date_empty: { value: 'SEND_DATE_EMPTY', label: 'Ngày thông báo không đúng' },
  user_group_reference_exists: { value: 'USER_GROUP_REFERENCE_EXISTS', label: 'Không thể xoá nhóm người dùng do có dữ liệu tham chiếu' },
  full_name_blank: { value: "FULL_NAME_BLANK", label: "Họ và tên không được để trống" },
  full_name_type_incorrect: { value: "FULL_NAME_TYPE_INCORRECT", label: "Họ và tên phải bao ngồm cả chữ" },
  full_name_max_length: { value: "FULL_NAME_MAX_LENGTH", label: "Họ và tên không được vượt quá 255 ký tự" },
  full_name_min_length: { value: "FULL_NAME_MIN_LENGTH", label: "Họ và tên phải ít nhất 3 ký tự" },
  full_name_all_space: { value: "FULL_NAME_ALL_SPACE", label: "Họ và tên không được để trống" },
  phone_blank: { value: "PHONE_BLANK", label: "Số điện thoại không được để trống" },
  phone_type_incorrect: { value: "PHONE_TYPE_INCORRECT", label: "Số điện thoại không đúng định dạng" },
  phone_max_length: { value: "PHONE_MAX_LENGTH", label: "Số điện thoại không đúng định dạng" },
  phone_min_length: { value: "PHONE_MIN_LENGTH", label: "Số điện thoại không đúng định dạng" },
  phone_all_space: { value: "PHONE_ALL_SPACE", label: "Số điện thoại không đúng định dạng" },
  phone_regex: { value: "PHONE_REGEX", label: "Số điện thoại không đúng định dạng" },
  phone_is_exist: { value: "PHONE_IS_EXIST", label: "Số điện thoại đã tồn tại" },
  email_blank: { value: "EMAIL_BLANK", label: "Email không được để trống" },
  email_type_incorrect: { value: "EMAIL_TYPE_INCORRECT", label: "Email không đúng định dạng" },
  email_max_length: { value: "EMAIL_MAX_LENGTH", label: "Email không đúng định dạng" },
  email_min_length: { value: "EMAIL_MIN_LENGTH", label: "Email không đúng định dạng" },
  email_all_space: { value: "EMAIL_ALL_SPACE", label: "Email không đúng định dạng" },
  email_regex: { value: "EMAIL_REGEX", label: "Email không đúng định dạng" },
  email_is_exist: { value: "EMAIL_IS_EXIST", label: "Email đã tồn tại" },
  user_group_blank: { value: "USER_GROUP_BLANK", label: "Nhóm người dùng không tồn tại" },
  user_group_is_not_exist: { value: "USER_GROUP_IS_NOT_EXIST", label: "Nhóm người dùng không tồn tại" },
  url_blank: { value: "URL_BLANK", label: "Url không được để trống" },
  url_type_incorrect: { value: "URL_TYPE_INCORRECT", label: "Url không đúng định dạng" },
  url_max_length: { value: "URL_MAX_LENGTH", label: "Url không đúng định dạng" },
  url_min_length: { value: "URL_MIN_LENGTH", label: "Url không đúng định dạng" },
  url_all_space: { value: "URL_ALL_SPACE", label: "Url không đúng định dạng" },
  url_regex: { value: "URL_REGEX", label: "Url không đúng định dạng" },
  url_is_exist: { value: "URL_IS_EXIST", label: "Url đã tồn tại" },
  name_blank: { value: "NAME_BLANK", label: "Tên nguồn không được để trống" },
  name_type_incorrect: { value: "NAME_TYPE_INCORRECT", label: "Tên nguồn phải bao ngồm cả chữ" },
  name_max_length: { value: "NAME_MAX_LENGTH", label: "Tên nguồn không được vượt quá 255 ký tự" },
  name_min_length: { value: "NAME_MIN_LENGTH", label: "Tên nguồn phải ít nhất 3 ký tự" },
  name_all_space: { value: "NAME_ALL_SPACE", label: "Tên nguồn không được để trống" },
  source_blank: { value: "SOURCE_BLANK", label: "Nguồn không được để trống" },
  source_max_length: { value: "SOURCE_MAX_LENGTH", label: "Nguồn không đúng định dạng" },
  source_min_length: { value: "SOURCE_MIN_LENGTH", label: "Nguồn không đúng định dạng" },
  source_all_space: { value: "SOURCE_ALL_SPACE", label: "Nguồn không đúng định dạng" },
  source_regex: { value: "SOURCE_REGEX", label: "Nguồn không đúng định dạng" },
  source_type_blank: { value: "SOURCE_TYPE_BLANK", label: "Loại nguồn không được để trống" },
  source_type_type_incorrect: { value: "SOURCE_TYPE_TYPE_INCORRECT", label: "Loại nguồn không đúng định dạng" },
  source_type_max_length: { value: "SOURCE_TYPE_MAX_LENGTH", label: "Loại nguồn không đúng định dạng" },
  source_type_min_length: { value: "SOURCE_TYPE_MIN_LENGTH", label: "Loại nguồn không đúng định dạng" },
  source_type_all_space: { value: "SOURCE_TYPE_ALL_SPACE", label: "Loại nguồn không đúng định dạng" },
  source_type_regex: { value: "SOURCE_TYPE_MIN_REGEX", label: "Loại nguồn không đúng định dạng" },
  source_group_regex: { value: "SOURCE_GROUP_REGEX", label: "Nhóm nguồn không đúng định dạng" },
  source_group_is_not_exist: { value: "SOURCE_GROUP_IS_NOT_EXIST", label: "Nhóm nguồn không tồn tại" },
  domain_blank: { value: "DOMAIN_BLANK", label: "Tên miền không được để trống" },
  domain_type_incorrect: { value: "DOMAIN_TYPE_INCORRECT", label: "Tên miền không đúng định dạng" },
  domain_max_length: { value: "DOMAIN_MAX_LENGTH", label: "Tên miền không đúng định dạng" },
  domain_min_length: { value: "DOMAIN_MIN_LENGTH", label: "Tên miền không đúng định dạng" },
  domain_all_space: { value: "DOMAIN_ALL_SPACE", label: "Tên miền không đúng định dạng" },
  domain_regex: { value: "DOMAIN_REGEX", label: "Tên miền không đúng định dạng" },
  domain_is_exist: { value: "DOMAIN_IS_EXIST", label: "Tên miền đã tồn tại" },
  domain_already_exists: { value: "DOMAIN_ALREADY_EXISTS", label: "Tên miền đã tồn tại" },
  start_url_blank: { value: "START_URL_BLANK", label: "URL bắt đầu không được để trống" },
  start_url_type_incorrect: { value: "START_URL_TYPE_INCORRECT", label: "URL bắt đầu không đúng định dạng" },
  start_url_max_length: { value: "START_URL_MAX_LENGTH", label: "URL bắt đầu không đúng định dạng" },
  start_url_min_length: { value: "START_URL_MIN_LENGTH", label: "URL bắt đầu không đúng định dạng" },
  start_url_all_space: { value: "START_URL_ALL_SPACE", label: "URL bắt đầu không đúng định dạng" },
  start_url_regex: { value: "START_URL_REGEX", label: "URL bắt đầu không đúng định dạng" },
  position_blank: { value: "POSITION_BLANK", label: "Vị trí không được để trống" },
  position_type_incorrect: { value: "POSITION_TYPE_INCORRECT", label: "Vị trí không đúng định dạng" },
  position_min_length: { value: "POSITION_MIN_LENGTH", label: "Vị trí phải ít nhất 1 ký tự" },
  position_all_space: { value: "POSITION_ALL_SPACE", label: "Vị trí không được để trống" },
  detector_blank: { value: "DETECTOR_BLANK", label: "Quy tắc không được để trống" },
  detector_type_incorrect: { value: "DETECTOR_TYPE_INCORRECT", label: "Quy tắc không đúng định dạng" },
  detector_min_length: { value: "DETECTOR_MIN_LENGTH", label: "Quy tắc phải ít nhất 1 ký tự" },
  detector_all_space: { value: "DETECTOR_ALL_SPACE", label: "Quy tắc không được để trống" },
  lot_name_blank: { value: "LOT_NAME_BLANK", label: "Tên lô không được để trống" },
  lot_name_type_incorrect: { value: "LOT_NAME_TYPE_INCORRECT", label: "Tên lô phải bao ngồm cả chữ" },
  lot_name_max_length: { value: "LOT_NAME_MAX_LENGTH", label: "Tên lô không được vượt quá 255 ký tự" },
  lot_name_min_length: { value: "LOT_NAME_MIN_LENGTH", label: "Tên lô phải ít nhất 1 ký tự" },
  lot_name_all_space: { value: "LOT_NAME_ALL_SPACE", label: "Tên lô không được để trống" },
  lot_description_max_length: { value: "LOT_DESCRIPTION_MAX_LENGTH", label: "Tên lô không được vượt quá 5000 ký tự" },
  lot_description_all_space: { value: "LOT_DESCRIPTION_ALL_SPACE", label: "Tên lô không được để trống" },
  user_has_account: { value: "USER_HAS_ACCOUNT", label: "Người dùng đã có tài khoản" },
  group_is_exist: { value: "GROUP_IS_EXIST", label: "Nhóm người dùng đã tồn tại" },
  url_malformed: { value: "URL_MALFORMED", label: "Url không đúng định dạng" },
  project_is_exist: { value: "PROJECT_IS_EXIST", label: "Chuyên đề đã tồn tại" },
  ntf_keyword_config_reference_exists: { value: "NTF_KEYWORD_CONFIG_REFERENCE_EXISTS", label: "Không thể xoá do có dữ liệu tham chiếu đến cấu hình thông báo từ khoá" },
  email_incorrect: { value: 'EMAIL_INCORRECT', label: 'email không đúng' },
  profile_incorrect: { value: 'PROFILE_INCORRECT', label: 'Không tìm thấy đối tượng' },
  function_not_found: { value: 'FUNCTION_NOT_FOUND', label: 'Không tìm thấy menu' },
  function_reference_exists: { value: 'FUNCTION_REFERENCE_EXISTS', label: 'Không thể ẩn menu, vì có menu con' },
  sentiment_keyword_not_found: { value: 'SENTIMENT_KEYWORD_NOT_FOUND', label: 'Không tìm thấy từ khoá sắc thái' },
  keyword_blank: { value: "KEYWORD_BLANK", label: "Từ khoá sắc thái không được để trống" },
  keyword_type_incorrect: { value: "KEYWORD_TYPE_INCORRECT", label: "Từ khoá sắc thái không đúng định dạng" },
  keyword_max_length: { value: "KEYWORD_MAX_LENGTH", label: "Từ khoá sắc thái không được vượt quá 255 ký tự" },
  keyword_min_length: { value: "KEYWORD_MIN_LENGTH", label: "Từ khoá sắc thái không được nhỏ hơn 3 ký tự" },
  keyword_all_space: { value: "KEYWORD_ALL_SPACE", label: "Từ khoá sắc thái không được để trống" },
  keyword_regex: { value: "KEYWORD_REGEX", label: "Từ khoá sắc thái đúng định dạng" },
  sentiment_blank: { value: "SENTIMENT_BLANK", label: "Sắc thái không được để trống" },
  sentiment_type_incorrect: { value: "SENTIMENT_TYPE_INCORRECT", label: "Sắc thái đúng định dạng" },
  sentiment_max_length: { value: "SENTIMENT_MAX_LENGTH", label: "Sắc thái không đúng định dạng" },
  sentiment_min_length: { value: "SENTIMENT_MIN_LENGTH", label: "Sắc thái không đúng định dạng" },
  sentiment_all_space: { value: "SENTIMENT_ALL_SPACE", label: "Sắc thái không được để trống" },
  sentiment_regex: { value: "SENTIMENT_REGEX", label: "Sắc thái đúng định dạng" },
  user_reference_account_exists: { value: "USER_REFERENCE_ACCOUNT_EXISTS", label: "Không thể xoá do có dữ liệu tham chiếu đến tài khoản đăng nhập" },
  name_project_blank: { value: "NAME_PROJECT_BLANK", label: "Tên chuyên đề không được để trống" },
  name_project_type_incorrect: { value: "NAME_PROJECT_TYPE_INCORRECT", label: "Tên chuyên đề không đúng định dạng" },
  name_project_min_length: { value: "NAME_PROJECT_MIN_LENGTH", label: "Tên chuyên đề phải ít nhất 3 ký tự" },
  name_project_max_length: { value: "NAME_PROJECT_MAX_LENGTH", label: "Tên chuyên đề không được vượt quá 255 ký tự" },
  name_project_all_space: { value: "NAME_PROJECT_ALL_SPACE", label: "Tên chuyên đề không được để trống" },
  main_keyword_blank: { value: "MAIN_KEYWORD_BLANK", label: "Tự khoá chính không được để trống" },
  main_keyword_type_incorrect: { value: "MAIN_KEYWORD_TYPE_INCORRECT", label: "Tự khoá chính không đúng định dạng" },
  main_keyword_all_space: { value: "MAIN_KEYWORD_ALL_SPACE", label: "Tự khoá chính không được để trống" },
  attach_keyword_all_space: { value: "ATTACH_KEYWORD", label: "Tự khoá đính kèm không được chỉ chứa dấu cách" },
  exclude_keyword_all_space: { value: "EXCLUDE_KEYWORD", label: "Tự khoá loại trừ không được chỉ chứa dấu cách" },
  source_config_type_incorrect: { value: "SOURCE_CONFIG_TYPE_INCORRECT", label: "Nguồn không đúng định dạng" },
  source_config_all_space: { value: "SOURCE_CONFIG_ALL_SPACE", label: "Nguồn không đúng định dạng" },
  source_config_regex: { value: "SOURCE_CONFIG_REGEX", label: "Nguồn không đúng định dạng" },
  profile_id_already_exists: { value: "PROFILE_ID_ALREADY_EXISTS", label: "Url đã tồn tại" },
  user_reference_ntf_exists: { value: "USER_REFERENCE_NTF_EXISTS", label: "Không thể xoá người dùng do có dữ liệu tham chiếu cấu hình thông báo" },
  user_deactive: { value: "USER_DEACTIVE", label: "Tài khoản đã bị khoá" },
}

export const ERR_MESSAGES = [
  ERR_MESSAGE.unauthorized,
  ERR_MESSAGE.forbidden,
  ERR_MESSAGE.user_invalid,
  ERR_MESSAGE.user_me_delete,
  ERR_MESSAGE.user_not_exist,
  ERR_MESSAGE.password_incorrect,
  ERR_MESSAGE.project_not_found,
  ERR_MESSAGE.social_obj_not_found,
  ERR_MESSAGE.social_source_not_found,
  ERR_MESSAGE.group_not_found,
  ERR_MESSAGE.post_not_found,
  ERR_MESSAGE.lot_not_found,
  ERR_MESSAGE.website_obj_not_found,
  ERR_MESSAGE.website_source_not_found,
  ERR_MESSAGE.internal_server_error,
  ERR_MESSAGE.note_lock,
  ERR_MESSAGE.lot_reference_exists,
  ERR_MESSAGE.group_reference_exists,
  ERR_MESSAGE.notification_config_not_found,
  ERR_MESSAGE.notification_config_reference_exists,
  ERR_MESSAGE.notification_not_found,
  ERR_MESSAGE.times_type_incorrect,
  ERR_MESSAGE.send_time_incorrect,
  ERR_MESSAGE.send_date_empty,
  ERR_MESSAGE.user_group_reference_exists,
  ERR_MESSAGE.full_name_blank,
  ERR_MESSAGE.full_name_type_incorrect,
  ERR_MESSAGE.full_name_max_length,
  ERR_MESSAGE.full_name_min_length,
  ERR_MESSAGE.full_name_all_space,
  ERR_MESSAGE.phone_blank,
  ERR_MESSAGE.phone_type_incorrect,
  ERR_MESSAGE.phone_max_length,
  ERR_MESSAGE.phone_min_length,
  ERR_MESSAGE.phone_all_space,
  ERR_MESSAGE.phone_regex,
  ERR_MESSAGE.phone_is_exist,
  ERR_MESSAGE.email_blank,
  ERR_MESSAGE.email_type_incorrect,
  ERR_MESSAGE.email_max_length,
  ERR_MESSAGE.email_min_length,
  ERR_MESSAGE.email_all_space,
  ERR_MESSAGE.email_regex,
  ERR_MESSAGE.email_is_exist,
  ERR_MESSAGE.user_group_is_not_exist,
  ERR_MESSAGE.user_group_blank,
  ERR_MESSAGE.url_blank,
  ERR_MESSAGE.url_type_incorrect,
  ERR_MESSAGE.url_max_length,
  ERR_MESSAGE.url_min_length,
  ERR_MESSAGE.url_all_space,
  ERR_MESSAGE.url_regex,
  ERR_MESSAGE.url_is_exist,
  ERR_MESSAGE.name_blank,
  ERR_MESSAGE.name_type_incorrect,
  ERR_MESSAGE.name_max_length,
  ERR_MESSAGE.name_min_length,
  ERR_MESSAGE.name_all_space,
  ERR_MESSAGE.source_blank,
  ERR_MESSAGE.source_max_length,
  ERR_MESSAGE.source_min_length,
  ERR_MESSAGE.source_all_space,
  ERR_MESSAGE.source_regex,
  ERR_MESSAGE.source_type_blank,
  ERR_MESSAGE.source_type_type_incorrect,
  ERR_MESSAGE.source_type_max_length,
  ERR_MESSAGE.source_type_min_length,
  ERR_MESSAGE.source_type_all_space,
  ERR_MESSAGE.source_type_regex,
  ERR_MESSAGE.source_group_regex,
  ERR_MESSAGE.source_group_is_not_exist,
  ERR_MESSAGE.domain_blank,
  ERR_MESSAGE.domain_type_incorrect,
  ERR_MESSAGE.domain_max_length,
  ERR_MESSAGE.domain_min_length,
  ERR_MESSAGE.domain_all_space,
  ERR_MESSAGE.domain_regex,
  ERR_MESSAGE.domain_is_exist,
  ERR_MESSAGE.start_url_blank,
  ERR_MESSAGE.start_url_type_incorrect,
  ERR_MESSAGE.start_url_max_length,
  ERR_MESSAGE.start_url_min_length,
  ERR_MESSAGE.start_url_all_space,
  ERR_MESSAGE.start_url_regex,
  ERR_MESSAGE.position_blank,
  ERR_MESSAGE.position_type_incorrect,
  ERR_MESSAGE.position_min_length,
  ERR_MESSAGE.position_all_space,
  ERR_MESSAGE.detector_blank,
  ERR_MESSAGE.detector_type_incorrect,
  ERR_MESSAGE.detector_min_length,
  ERR_MESSAGE.detector_all_space,
  ERR_MESSAGE.lot_name_blank,
  ERR_MESSAGE.lot_name_type_incorrect,
  ERR_MESSAGE.lot_name_max_length,
  ERR_MESSAGE.lot_name_min_length,
  ERR_MESSAGE.lot_name_all_space,
  ERR_MESSAGE.lot_description_all_space,
  ERR_MESSAGE.lot_description_max_length,
  ERR_MESSAGE.user_has_account,
  ERR_MESSAGE.group_is_exist,
  ERR_MESSAGE.url_malformed,
  ERR_MESSAGE.project_is_exist,
  ERR_MESSAGE.ntf_keyword_config_reference_exists,
  ERR_MESSAGE.email_incorrect,
  ERR_MESSAGE.profile_incorrect,
  ERR_MESSAGE.function_not_found,
  ERR_MESSAGE.function_reference_exists,
  ERR_MESSAGE.sentiment_keyword_not_found,
  ERR_MESSAGE.keyword_blank,
  ERR_MESSAGE.keyword_type_incorrect,
  ERR_MESSAGE.keyword_max_length,
  ERR_MESSAGE.keyword_min_length,
  ERR_MESSAGE.keyword_all_space,
  ERR_MESSAGE.keyword_regex,
  ERR_MESSAGE.sentiment_blank,
  ERR_MESSAGE.sentiment_type_incorrect,
  ERR_MESSAGE.sentiment_max_length,
  ERR_MESSAGE.sentiment_min_length,
  ERR_MESSAGE.sentiment_all_space,
  ERR_MESSAGE.sentiment_regex,
  ERR_MESSAGE.user_reference_account_exists,
  ERR_MESSAGE.name_project_blank,
  ERR_MESSAGE.name_project_type_incorrect,
  ERR_MESSAGE.name_project_min_length,
  ERR_MESSAGE.name_project_max_length,
  ERR_MESSAGE.name_project_all_space,
  ERR_MESSAGE.main_keyword_blank,
  ERR_MESSAGE.main_keyword_type_incorrect,
  ERR_MESSAGE.main_keyword_all_space,
  ERR_MESSAGE.attach_keyword_all_space,
  ERR_MESSAGE.exclude_keyword_all_space,
  ERR_MESSAGE.exclude_keyword_all_space,
  ERR_MESSAGE.source_config_type_incorrect,
  ERR_MESSAGE.source_config_all_space,
  ERR_MESSAGE.source_config_regex,
  ERR_MESSAGE.profile_id_already_exists,
]

export const ERR_MESSAGE_LABEL = (err: string) => {
  const index = ERR_MESSAGES.findIndex(e => e.value === err);
  if (index > -1) {
    return ERR_MESSAGES[index].label;
  }
  return err;
}
