

export enum EREPORT {
    MENTION_TIME = 'MENTION_TIME',
    MENTION_SOURCE = 'MENTION_SOURCE',
    SENTIMENT = 'SENTIMENT',
    RATIO_SENTIMENT = 'RATIO_SENTIMENT',
    SPREAD = 'SPREAD',
    RATIO_SOURCE = 'RATIO_SOURCE',
    TOP_POST = 'TOP_POST',
    TOP_USER = 'TOP_USER',
    TOP_PAGE = 'TOP_PAGE',
    TOP_WEB = 'TOP_WEB',
    GENDER = 'GENDER',
    AGE = 'AGE',
    MARRIAGE = 'MARRIAGE',
    AREA = 'AREA',
    JOB = 'JOB',
    EDUCATION = 'EDUCATION',
    MENTION_ALL = 'MENTION_ALL',
    SENTIMENT_ALL = 'SENTIMENT_ALL',
    TOPIC_MENTION = 'TOPIC_MENTION',
    TOPIC_INTERACT = 'TOPIC_INTERACT',
    PROFILE_MENTION = 'PROFILE_MENTION',
    PROFILE_INTERACT = 'PROFILE_INTERACT',
    POST_INTERACT = 'POST_INTERACT',
    GENDER_ALL = 'GENDER_ALL',
    AGE_ALL = 'AGE_ALL',
    MARRIAGE_ALL = 'MARRIAGE_ALL',
    AREA_ALL = 'AREA_ALL'
}

export const ReportLabel: { [key: string]: string } = {
    MENTION_TIME: 'Lượt đề cập đến chuyên đề theo thời gian',
    MENTION_SOURCE: 'Lượt đề cập đến chuyên đề theo nguồn tin',
    SENTIMENT: 'Diễn biến sắc thái của chuyên đề',
    RATIO_SENTIMENT: 'Tỉ lệ sắc thái của chuyên đề',
    SPREAD: 'Độ lan tỏa của chuyên đề',
    RATIO_SOURCE: 'Tỷ lệ nguồn tin liên quan đến chuyên đề',
    TOP_POST: 'Top tin bài tiêu biểu trong chuyên đề',
    TOP_USER: 'Top tác giả trong chuyên đề',
    TOP_PAGE: 'Top trang tin mạng xã hội trong chuyên đề',
    TOP_WEB: 'Top trang báo điện tử trong chuyên đề',
    GENDER: 'Nhân khẩu học theo giới tính trong chuyên đề',
    AGE: 'Nhân khẩu học theo độ tuổi trong chuyên đề',
    MARRIAGE: 'Nhân khẩu học theo tình trạng hôn nhân trong chuyên đề',
    AREA: 'Nhân khẩu học theo phân bố vùng miền trong chuyên đề',
    JOB: 'Nhân khẩu học theo nghề nghiệp trong chuyên đề',
    EDUCATION: 'Nhân khẩu học theo học vấn trong chuyên đề',
    MENTION_ALL: 'Lượt đề cập đến tất cả chuyên đề',
    SENTIMENT_ALL: 'Diễn biến sắc thái tất cả chuyên đề',
    TOPIC_MENTION: 'Top chuyên đề có lượng đề cập lớn nhất',
    TOPIC_INTERACT: 'Top chuyên đề có nhiều tương tác nhất',
    PROFILE_MENTION: 'Top nguồn tin đăng tải nhiều nhất',
    PROFILE_INTERACT: 'Top nguồn tin có nhiều tương tác nhất',
    POST_INTERACT: 'Top tin bài tiêu biểu',
    GENDER_ALL: 'Thống kê nhân khẩu học theo giới tính',
    AGE_ALL: 'Thống kê nhân khẩu học theo độ tuổi',
    MARRIAGE_ALL: 'Thống kê nhân khẩu học theo tình trạng hôn nhân',
    AREA_ALL: 'Thống kê nhân khẩu học theo phân bố vùng miền'
}